#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib.sh"

usage() {
  cat <<USAGE
Usage:
  $0 <server_name> [options]

Options:
  --display-name NAME
  --template NAME
  --game-port PORT
  --rcon-port PORT
  --rcon-password PASS
  --activate
USAGE
  exit 1
}

SERVER="${1:-}"
shift || true
[[ -n "${SERVER}" ]] || usage
sanitize_server_name "${SERVER}"

DISPLAY="${DEFAULT_DISPLAY_NAME}"
TEMPLATE="${DEFAULT_TEMPLATE_NAME}"
GAME_PORT_VALUE="${DEFAULT_GAME_PORT}"
RCON_PORT_VALUE="${DEFAULT_RCON_PORT}"
RCON_PASSWORD_VALUE="${DEFAULT_RCON_PASSWORD}"
ACTIVATE="no"

while (( "$#" )); do
  case "$1" in
    --display-name) DISPLAY="${2:-}"; shift 2 ;;
    --template) TEMPLATE="${2:-}"; shift 2 ;;
    --game-port) GAME_PORT_VALUE="${2:-}"; shift 2 ;;
    --rcon-port) RCON_PORT_VALUE="${2:-}"; shift 2 ;;
    --rcon-password) RCON_PASSWORD_VALUE="${2:-}"; shift 2 ;;
    --activate) ACTIVATE="yes"; shift ;;
    *) die "unknown option: $1" ;;
  esac
done

CONF="$(server_conf_path "${SERVER}")"
[[ ! -f "${CONF}" ]] || die "config already exists: ${CONF}"

cat > "${CONF}" <<CONFIG_EOF
#!/usr/bin/env bash
SERVER_NAME="${SERVER}"
DISPLAY_NAME="${DISPLAY}"
SERVER_DIR="${SERVERS_DIR}/${SERVER}"
WORLD_DIR="${SERVERS_DIR}/${SERVER}/world"

TEMPLATE_NAME="${TEMPLATE}"
MODPACK_NAME=""
MODPACK_VERSION=""

TMUX_SESSION="mc-${SERVER}"
SERVICE_NAME="minecraft-${SERVER}"

JAVA_BIN="${DEFAULT_JAVA_BIN}"
MCRCON="${DEFAULT_MCRCON}"

GAME_PORT="${GAME_PORT_VALUE}"
RCON_HOST="${DEFAULT_RCON_HOST}"
RCON_PORT="${RCON_PORT_VALUE}"
RCON_PASSWORD="${RCON_PASSWORD_VALUE}"

LOCAL_BACKUP_DIR="${LOCAL_BACKUPS_DIR}/${SERVER}"
BACKUP_MANIFEST_DIR="${BACKUP_MANIFESTS_DIR}/${SERVER}"
RESTORE_WORK_DIR="${RESTORE_DIR}/${SERVER}"

BACKUP_ON_CALENDAR="${DEFAULT_BACKUP_ON_CALENDAR}"
ENABLE_SCHEDULED_RESTARTS="${DEFAULT_ENABLE_SCHEDULED_RESTARTS}"
RESTART_ON_CALENDAR="${DEFAULT_RESTART_ON_CALENDAR}"

ENABLE_RESTART_WARNINGS="${DEFAULT_ENABLE_RESTART_WARNINGS}"
RESTART_WARNING_INTERVALS="${DEFAULT_RESTART_WARNING_INTERVALS}"
FINAL_RESTART_WARNING_SECONDS="${DEFAULT_FINAL_RESTART_WARNING_SECONDS}"

KEEP_HOURLY="${DEFAULT_KEEP_HOURLY}"
KEEP_DAILY="${DEFAULT_KEEP_DAILY}"
KEEP_WEEKLY="${DEFAULT_KEEP_WEEKLY}"

ENABLE_OFFSITE_BACKUP="${DEFAULT_ENABLE_OFFSITE_BACKUP}"
OFFSITE_TARGET="${DEFAULT_OFFSITE_TARGET}"

SHUTDOWN_TIMEOUT="${DEFAULT_SHUTDOWN_TIMEOUT}"
MAX_BACKUP_AGE_HOURS="${DEFAULT_MAX_BACKUP_AGE_HOURS}"
CRASH_LOCK_THRESHOLD="${DEFAULT_CRASH_LOCK_THRESHOLD}"
CRASH_LOCK_WINDOW_MINUTES="${DEFAULT_CRASH_LOCK_WINDOW_MINUTES}"
CRASH_RESTART_BACKOFF_SECONDS="${DEFAULT_CRASH_RESTART_BACKOFF_SECONDS}"

MIN_FREE_MB_START="${DEFAULT_MIN_FREE_MB_START}"
MIN_FREE_MB_BACKUP="${DEFAULT_MIN_FREE_MB_BACKUP}"
MIN_FREE_MB_RESTORE="${DEFAULT_MIN_FREE_MB_RESTORE}"

START_SCRIPT_NAME="${DEFAULT_START_SCRIPT_NAME}"
UNIX_ARGS_FILE="${DEFAULT_UNIX_ARGS_FILE}"
SERVER_JAR=""
CONFIG_EOF

chmod 0644 "${CONF}"
mkdir -p "${SERVERS_DIR}/${SERVER}" "${LOCAL_BACKUPS_DIR}/${SERVER}" "${BACKUP_MANIFESTS_DIR}/${SERVER}" "${RESTORE_DIR}/${SERVER}"
safe_copy_template_if_missing "${TEMPLATE}" "${SERVERS_DIR}/${SERVER}"

"${SCRIPT_DIR}/validate-server-config.sh" "${SERVER}"

if [[ "${ACTIVATE}" == "yes" ]]; then
  set_active_server "${SERVER}"
fi

echo "Created config: ${CONF}"
